apiVersion: batch/v1
kind: Job
metadata:
  name: txcmedia-job
spec:
  template:
    spec:
      containers:
      - name: txcmedia-job
        image: yash5090/txcmedia:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
