apiVersion: apps/v1
kind: Deployment
metadata:
  name: txcmedia-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: txcmedia
  template:
    metadata:
      labels:
        app: txcmedia
    spec:
      containers:
        - name: txcmedia
          image: yash5090/txcmedia:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
